
/*
 * 注意：
 * 这里只是举了个示例，具体参数值，需要根据实际情况定义
 */


/*郑州、新河南、河北、黑龙江、吉林、江西、辽宁、本溪、天津、山东、甘肃、陕西、山西、安徽、
 江苏、广西、广东、云南、福建、襄阳、北镇、湖南、大同  */
var mapObj = {};//外层集合对象，存放地区编码以及对应的地区系统编码域名集合对象
//河南
var map_henan = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_henan["portal"]="http://henan.czbanbantong.com";
map_henan["pls"]="http://plshenan.czbanbantong.com";
map_henan["cms"]="http://vfshenan.czbanbantong.com";
map_henan["tms"]="http://tmshenan.czbanbantong.com";
map_henan["tqms"]="http://tqmshenan.czbanbantong.com";
map_henan["sso"]="http://ssohenan.czbanbantong.com";
map_henan["ilearn"]="http://ilearnhenan.czbanbantong.com";
map_henan["eng"]="http://en.czbanbantong.com";
map_henan["statpv"]="statpvhenan.czbanbantong.com";
map_henan["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_henan["nbsy"]="http://nbhenan.czbanbantong.com/experiment/index/wuli?sso=b502be4bad42c52a5bfbf6e4775ab4e40a1f89119f60218f7d0feb6e27880bef&sso_ip=65a13da4931d082a596f9bb4167e6a7a";
map_henan["gkzy"]="http://zz.api.ks5u.com";
map_henan["ubi"]="http://ubhenan.czbanbantong.com";
map_henan["micro"]="http://wkhenan.czbanbantong.com";
map_henan["vfs"]="http://vfshenan.czbanbantong.com";
map_henan["area"]="henan";
	//河南的其他系统域名可以根据上面的继续往下配置
map_henan["pingk"]="http://pkhenan.czbanbantong.com";
mapObj["25."]=map_henan;
//许昌
var map_xc = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_xc["portal"]="http://xc.czbanbantong.com";
map_xc["pls"]="http://plsxc.czbanbantong.com";
map_xc["cms"]="http://vfsxc.czbanbantong.com";
map_xc["tms"]="http://tmsxc.czbanbantong.com";
map_xc["tqms"]="http://tqmsxc.czbanbantong.com";
map_xc["sso"]="http://ssoxc.czbanbantong.com";
map_xc["ilearn"]="http://ilearnxc.czbanbantong.com";
map_xc["eng"]="http://en.czbanbantong.com";
map_xc["statpv"]="statpvxc.czbanbantong.com";
map_xc["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_xc["ysyyk"]="http://125.46.40.226";
map_xc["nbsy"]="http://nbxc.czbanbantong.com/experiment/index/wuli?sso=3fb3f77a30c1193c16240e7ba41c291940c1b0e013ef750c&sso_ip=269678b75e21a2fb0821e526d897fcd8";
map_xc["gkzy"]="http://zz.api.ks5u.com";
map_xc["pingk"]="http://pkhenan.czbanbantong.com";
map_xc["ubi"]="http://ubxc.czbanbantong.com";
map_xc["micro"]="http://wkxc.czbanbantong.com";
map_xc["vfs"]="http://vfsxc.czbanbantong.com";
map_xc["area"]="xc";	
mapObj["27."]=map_xc;

//鹤壁20150512增加共建河南
var map_hebi = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_hebi["portal"]="http://hebi.czbanbantong.com";
map_hebi["pls"]="http://plshenan.czbanbantong.com";
map_hebi["cms"]="http://vfshenan.czbanbantong.com";
map_hebi["tms"]="http://tmshenan.czbanbantong.com";
map_hebi["tqms"]="http://tqmshenan.czbanbantong.com";
map_hebi["sso"]="http://ssohebi.czbanbantong.com";
map_hebi["ilearn"]="http://ilearnhenan.czbanbantong.com";
map_hebi["eng"]="http://en.czbanbantong.com";
map_hebi["statpv"]="statpvhenan.czbanbantong.com";
map_hebi["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_hebi["nbsy"]="http://nbhenan.czbanbantong.com/experiment/index/wuli?sso=b502be4bad42c52a5bfbf6e4775ab4e40a1f89119f60218f7d0feb6e27880bef&sso_ip=65a13da4931d082a596f9bb4167e6a7a";
map_hebi["gkzy"]="http://zz.api.ks5u.com";
map_hebi["pingk"]="http://pkhenan.czbanbantong.com";
map_hebi["ubi"]="http://ubhenan.czbanbantong.com";
map_hebi["micro"]="http://wkhenan.czbanbantong.com";
map_hebi["vfs"]="http://vfshenan.czbanbantong.com";
map_hebi["area"]="hebi";
mapObj["35."]=map_hebi;

//永城20150214增加
var map_yc = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_yc["portal"]="http://yc.czbanbantong.com";
map_yc["pls"]="http://plsyc.czbanbantong.com";
map_yc["cms"]="http://vfsyc.czbanbantong.com";
map_yc["tms"]="http://tmsyc.czbanbantong.com";
map_yc["tqms"]="http://tqmsyc.czbanbantong.com";
map_yc["sso"]="http://ssoyc.czbanbantong.com";
map_yc["ilearn"]="http://ilearnyc.czbanbantong.com";
map_yc["eng"]="http://en.czbanbantong.com";
map_yc["statpv"]="statpvyc.czbanbantong.com";
map_yc["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_yc["nbsy"]="http://nbyc.czbanbantong.com/experiment/index/wuli?sso=b502be4bad42c52a5bfbf6e4775ab4e40a1f89119f60218f7d0feb6e27880bef&sso_ip=65a13da4931d082a596f9bb4167e6a7a";
map_yc["gkzy"]="http://zz.api.ks5u.com";
map_yc["pingk"]="http://pkyc.czbanbantong.com";
map_yc["vfs"]="http://vfsyc.czbanbantong.com";
map_yc["ubi"]="http://ubyc.czbanbantong.com";
map_yc["micro"]="http://wkyc.czbanbantong.com";
map_yc["area"]="yc";
mapObj["40."]=map_yc;


var map_zhengzhou = {};   //内层集合对象，存放河北地区系统编码以及对应的域名
map_zhengzhou["portal"]="http://zz.zzedu.net.cn";
map_zhengzhou["pls"]="http://plszz.zzedu.net.cn";
map_zhengzhou["cms"]="http://vfszz.zzedu.net.cn";
map_zhengzhou["cmsq"]="http://cms.czbanbantong.com";
map_zhengzhou["tms"]="http://tmszz.zzedu.net.cn";
map_zhengzhou["tqms"]="http://tqmszz.zzedu.net.cn";
map_zhengzhou["sso"]="http://ssozz.zzedu.net.cn";
map_zhengzhou["ilearn"]="http://ilearnzz.zzedu.net.cn";
map_zhengzhou["eng"]="http://enzz.zzedu.net.cn";
map_zhengzhou["statpv"]="statpvzz.zzedu.net.cn";
map_zhengzhou["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_zhengzhou["nbsy"]="http://nbzz.zzedu.net.cn/experiment/index/wuli?sso=82aa48a71441f465c3fb3d61565c37c23d9a215273c06576&sso_ip=6b4fb9e329ee8f7d9fc6c89e32e1fa15";
map_zhengzhou["gkzy"]="http://zz.api.ks5u.com";
map_zhengzhou["pingk"]="http://pkzz.zzedu.net.cn";	
map_zhengzhou["ubi"]="http://ubzz.zzedu.net.cn";
map_zhengzhou["vfs"]="http://vfszz.zzedu.net.cn";
map_zhengzhou["micro"]="http://wkzz.zzedu.net.cn";
map_zhengzhou["area"]="zhengzhou";
mapObj["1."]=map_zhengzhou;

//mapObj["1."]["pls"]; //获取

//福建
var map_fj = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_fj["portal"]="http://fj.czbanbantong.com";
map_fj["pls"]="http://plsfj.czbanbantong.com";
map_fj["cms"]="http://vfsfj.czbanbantong.com";
map_fj["tms"]="http://tmsfj.czbanbantong.com";
map_fj["tqms"]="http://tqmsfj.czbanbantong.com";
map_fj["sso"]="http://ssofj.czbanbantong.com";
map_fj["ilearn"]="http://ilearnfj.czbanbantong.com";
map_fj["eng"]="http://en.czbanbantong.com";
map_fj["statpv"]="statpvfj.czbanbantong.com";
map_fj["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_fj["nbsy"]="http://nbfj.czbanbantong.com/experiment/index/wuli?sso=af80cfc9dd39b663566839ced990580c51c715ed1f1d6f23&sso_ip=a375f58263714f6b24ccee3b40553a1d";
map_fj["gkzy"]="http://zz.api.ks5u.com";
map_fj["pingk"]="http://pkfj.czbanbantong.com";
map_fj["ubi"]="http://ubfj.czbanbantong.com";
map_fj["vfs"]="http://vfsfj.czbanbantong.com";
map_fj["micro"]="http://wkfj.czbanbantong.com";
map_fj["area"]="fj";
mapObj["2."]=map_fj;

//河北
var map_he = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_he["portal"]="http://he.czbanbantong.com";
map_he["pls"]="http://plshe.czbanbantong.com";
map_he["cms"]="http://vfshe.czbanbantong.com";
map_he["tms"]="http://tmshe.czbanbantong.com";
map_he["tqms"]="http://tqmshe.czbanbantong.com";
map_he["sso"]="http://ssohe.czbanbantong.com";
map_he["ilearn"]="http://ilearnhe.czbanbantong.com";
map_he["eng"]="http://en.czbanbantong.com";
map_he["statpv"]="statpvhe.czbanbantong.com";
map_he["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_he["nbsy"]="http://nbhe.czbanbantong.com/experiment/index/wuli?sso=0249b527e27a312d35944708451c38db0565f25c7d1c290f&sso_ip=a375f58263714f6bf0fda172ec4786dd";
map_he["gkzy"]="http://zz.api.ks5u.com";
map_he["pingk"]="http://pkhe.czbanbantong.com";
map_he["ubi"]="http://ubhe.czbanbantong.com";
map_he["vfs"]="http://vfshe.czbanbantong.com";
map_he["micro"]="http://wkhe.czbanbantong.com";
map_he["area"]="he";
mapObj["3."]=map_he;
//黑龙江
var map_hl = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_hl["portal"]="http://hl.czbanbantong.com";
map_hl["pls"]="http://plshl.czbanbantong.com";
map_hl["cms"]="http://vfshl.czbanbantong.com";
map_hl["tms"]="http://tmshl.czbanbantong.com";
map_hl["tqms"]="http://tqmshl.czbanbantong.com";
map_hl["sso"]="http://ssohl.czbanbantong.com";
map_hl["ilearn"]="http://ilearnhl.czbanbantong.com";
map_hl["eng"]="http://en.czbanbantong.com";
map_hl["statpv"]="statpvhl.czbanbantong.com";
map_hl["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_hl["nbsy"]="http://nbhl.czbanbantong.com/experiment/index/wuli?sso=56880e711d0b62e8fdcb0a04beff8e41ce1a779fa54281ae&sso_ip=09cbab7a85d5bad24812470aa25e7a63";
map_hl["gkzy"]="http://zz.api.ks5u.com";
map_hl["pingk"]="http://pkhl.czbanbantong.com";
map_hl["ubi"]="http://ubhl.czbanbantong.com";
map_hl["vfs"]="http://vfshl.czbanbantong.com";
map_hl["micro"]="http://wkhl.czbanbantong.com";
map_hl["area"]="hl";
mapObj["6."]=map_hl;

//黑龙江龙江县
var map_lj = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_lj["portal"]="http://lj.czbanbantong.com";
map_lj["pls"]="http://plshl.czbanbantong.com";
map_lj["cms"]="http://vfshl.czbanbantong.com";
map_lj["tms"]="http://tmshl.czbanbantong.com";
map_lj["tqms"]="http://tqmshl.czbanbantong.com";
map_lj["sso"]="http://ssolj.czbanbantong.com";
map_lj["ilearn"]="http://ilearnhl.czbanbantong.com";
map_lj["eng"]="http://en.czbanbantong.com";
map_lj["statpv"]="statpvhl.czbanbantong.com";
map_lj["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_lj["nbsy"]="http://nbhl.czbanbantong.com/experiment/index/wuli?sso=56880e711d0b62e8fdcb0a04beff8e41ce1a779fa54281ae&sso_ip=09cbab7a85d5bad24812470aa25e7a63";
map_lj["gkzy"]="http://zz.api.ks5u.com";
map_lj["pingk"]="http://pkhl.czbanbantong.com";
map_lj["vfs"]="http://vfshl.czbanbantong.com";
map_lj["ubi"]="http://ubhl.czbanbantong.com";
map_lj["micro"]="http://wkhl.czbanbantong.com";
map_lj["area"]="lj";
mapObj["39."]=map_lj;

//大兴安岭
var map_dxal = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_dxal["portal"]="http://dxal.czbanbantong.com";
map_dxal["pls"]="http://plsdxal.czbanbantong.com";
map_dxal["cms"]="http://vfshl.czbanbantong.com";
map_dxal["tms"]="http://tmshl.czbanbantong.com";
map_dxal["tqms"]="http://tqmshl.czbanbantong.com";
map_dxal["sso"]="http://ssodxal.czbanbantong.com";
map_dxal["ilearn"]="http://ilearnhl.czbanbantong.com";
map_dxal["eng"]="http://en.czbanbantong.com";
map_dxal["statpv"]="statpvhl.czbanbantong.com";
map_dxal["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_dxal["nbsy"]="http://nbhl.czbanbantong.com/experiment/index/wuli?sso=56880e711d0b62e8fdcb0a04beff8e41ce1a779fa54281ae&sso_ip=09cbab7a85d5bad24812470aa25e7a63";
map_dxal["gkzy"]="http://zz.api.ks5u.com";
map_dxal["pingk"]="http://pkhl.czbanbantong.com";
map_dxal["ubi"]="http://ubhl.czbanbantong.com";
map_dxal["vfs"]="http://vfshl.czbanbantong.com";
map_dxal["micro"]="http://wkhl.czbanbantong.com";
map_dxal["area"]="dxal";
mapObj["41."]=map_dxal;

//山东
var map_sd = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_sd["portal"]="http://sd.czbanbantong.com";
map_sd["pls"]="http://plssd.czbanbantong.com";
map_sd["cms"]="http://vfssd.czbanbantong.com";
map_sd["tms"]="http://tmssd.czbanbantong.com";
map_sd["tqms"]="http://tqmssd.czbanbantong.com";
map_sd["sso"]="http://ssosd.czbanbantong.com";
map_sd["ilearn"]="http://ilearnsd.czbanbantong.com";
map_sd["eng"]="http://en.czbanbantong.com";
map_sd["statpv"]="statpvsd.czbanbantong.com";
map_sd["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_sd["nbsy"]="http://nbsd.czbanbantong.com/experiment/index/wuli?sso=3bc7e7419e18bb23efd3c2cd2ed8b9ee83641f013b15e84e&sso_ip=1d51730975dd162a3c4d15e9200a38a7";
map_sd["gkzy"]="http://zz.api.ks5u.com";
map_sd["pingk"]="http://pksd.czbanbantong.com";
map_sd["ubi"]="http://ubsd.czbanbantong.com";
map_sd["vfs"]="http://vfssd.czbanbantong.com";
map_sd["micro"]="http://wksd.czbanbantong.com";
map_sd["area"]="sd";
mapObj["4."]=map_sd;

//吉林
var map_jl = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_jl["portal"]="http://jl.czbanbantong.com";
map_jl["pls"]="http://plsjl.czbanbantong.com";
map_jl["cms"]="http://vfsjl.czbanbantong.com";
map_jl["tms"]="http://tmsjl.czbanbantong.com";
map_jl["tqms"]="http://tqmsjl.czbanbantong.com";
map_jl["sso"]="http://ssojl.czbanbantong.com";
map_jl["ilearn"]="http://ilearnjl.czbanbantong.com";
map_jl["eng"]="http://en.czbanbantong.com";
map_jl["statpv"]="statpvjl.czbanbantong.com";
map_jl["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_jl["nbsy"]="http://nbjl.czbanbantong.com/experiment/index/wuli?sso=aae0080f3824a74275d9f3b537898d6f853d03cd1cecbc16&sso_ip=d9cbbdac0b400439b669b53fda5b93ff";
map_jl["gkzy"]="http://zz.api.ks5u.com";
map_jl["pingk"]="http://pkjl.czbanbantong.com";
map_jl["ubi"]="http://ubjl.czbanbantong.com";
map_jl["vfs"]="http://vfsjl.czbanbantong.com";
map_jl["micro"]="http://wkjl.czbanbantong.com";
map_jl["area"]="jl";
mapObj["7."]=map_jl;

//浙江
var map_zj = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_zj["portal"]="http://zj.czbanbantong.com";
map_zj["pls"]="http://plszj.czbanbantong.com";
map_zj["cms"]="http://vfszj.czbanbantong.com";
map_zj["tms"]="http://tmszj.czbanbantong.com";
map_zj["tqms"]="http://tqmszj.czbanbantong.com";
map_zj["sso"]="http://ssozj.czbanbantong.com";
map_zj["ilearn"]="http://ilearnzj.czbanbantong.com";
map_zj["eng"]="http://en.czbanbantong.com";
map_zj["statpv"]="statpvzj.czbanbantong.com";
map_zj["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_zj["nbsy"]="http://nbzj.czbanbantong.com/experiment/index/wuli?sso=77290dce80ca395ee614f32919e7a4b92129defead86a91e&sso_ip=a375f58263714f6b6d25da4baf80a428";
map_zj["gkzy"]="http://zz.api.ks5u.com";
map_zj["pingk"]="http://pkzj.czbanbantong.com";
map_zj["ubi"]="http://ubzj.czbanbantong.com";
map_zj["vfs"]="http://vfszj.czbanbantong.com";
map_zj["micro"]="http://wkzj.czbanbantong.com";
map_zj["area"]="zj";
mapObj["8."]=map_zj;
//江西
var map_jx = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_jx["portal"]="http://jx.czbanbantong.com";
map_jx["pls"]="http://plsjx.czbanbantong.com";
map_jx["cms"]="http://vfsjx.czbanbantong.com";
map_jx["tms"]="http://tmsjx.czbanbantong.com";
map_jx["tqms"]="http://tqmsjx.czbanbantong.com";
map_jx["sso"]="http://ssojx.czbanbantong.com";
map_jx["ilearn"]="http://ilearnjx.czbanbantong.com";
map_jx["eng"]="http://en.czbanbantong.com";
map_jx["statpv"]="statpvjx.czbanbantong.com";
map_jx["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_jx["nbsy"]="http://nbjx.czbanbantong.com/experiment/index/wuli?sso=255a3b3b25e71b630ca6b2f0ea6a031b9253ba3ee2bf64a3&sso_ip=db62bab7d1b4a508969c96d09750e737";
map_jx["gkzy"]="http://zz.api.ks5u.com";
map_jx["pingk"]="http://pkjx.czbanbantong.com";
map_jx["ubi"]="http://ubjx.czbanbantong.com";
map_jx["vfs"]="http://vfsjx.czbanbantong.com";
map_jx["micro"]="http://wkjx.czbanbantong.com";
map_jx["area"]="jx";
mapObj["13."]=map_jx;
//辽宁
var map_ln = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_ln["portal"]="http://ln.czbanbantong.com";
map_ln["pls"]="http://plsln.czbanbantong.com";
map_ln["cms"]="http://vfsln.czbanbantong.com";
map_ln["tms"]="http://tmsln.czbanbantong.com";
map_ln["tqms"]="http://tqmsln.czbanbantong.com";
map_ln["sso"]="http://ssoln.czbanbantong.com";
map_ln["ilearn"]="http://ilearnln.czbanbantong.com";
map_ln["eng"]="http://en.czbanbantong.com";
map_ln["statpv"]="statpvln.czbanbantong.com";
map_ln["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_ln["nbsy"]="http://nbln.czbanbantong.com/experiment/index/wuli?sso=5dab51abcc1491bff22fc80d902bb252d6f9c5399fea26e7&sso_ip=65a13da4931d082a88fc6afe3aa9a675";
map_ln["gkzy"]="http://zz.api.ks5u.com";
map_ln["pingk"]="http://pkln.czbanbantong.com";
map_ln["ubi"]="http://ubln.czbanbantong.com";
map_ln["vfs"]="http://vfsln.czbanbantong.com";
map_ln["micro"]="http://wkln.czbanbantong.com";
map_ln["area"]="ln";
mapObj["16."]=map_ln;

//辽宁本溪共建辽宁
var map_bx = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_bx["portal"]="http://bxjyw.czbanbantong.com";
map_bx["pls"]="http://plsln.czbanbantong.com";
map_bx["cms"]="http://vfsln.czbanbantong.com";
map_bx["tms"]="http://tmsln.czbanbantong.com";
map_bx["tqms"]="http://tqmsln.czbanbantong.com";
map_bx["sso"]="http://ssoln.czbanbantong.com";
map_bx["ilearn"]="http://ilearnln.czbanbantong.com";
map_bx["eng"]="http://en.czbanbantong.com";
map_bx["statpv"]="statpvln.czbanbantong.com";
map_bx["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_bx["nbsy"]="http://nbln.czbanbantong.com/experiment/index/wuli?sso=5dab51abcc1491bff22fc80d902bb252d6f9c5399fea26e7&sso_ip=65a13da4931d082a88fc6afe3aa9a675";
map_bx["gkzy"]="http://zz.api.ks5u.com";
map_bx["pingk"]="http://pkln.czbanbantong.com";
map_bx["ubi"]="http://ubln.czbanbantong.com";
map_bx["vfs"]="http://vfsln.czbanbantong.com";
map_bx["micro"]="http://wkln.czbanbantong.com";
map_bx["area"]="bx";
mapObj["30."]=map_bx;

//辽宁营口20160311共建辽宁
var map_lnyk = {};   
map_lnyk["portal"]="http://lnyk.czbanbantong.com";
map_lnyk["pls"]="http://plsln.czbanbantong.com";
map_lnyk["cms"]="http://vfsln.czbanbantong.com";
map_lnyk["tms"]="http://tmsln.czbanbantong.com";
map_lnyk["tqms"]="http://tqmsln.czbanbantong.com";
map_lnyk["sso"]="http://ssolnyk.czbanbantong.com";
map_lnyk["ilearn"]="http://ilearnln.czbanbantong.com";
map_lnyk["eng"]="http://en.czbanbantong.com";
map_lnyk["statpv"]="statpvln.czbanbantong.com";
map_lnyk["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_lnyk["nbsy"]="http://nbln.czbanbantong.com/experiment/index/wuli?sso=5dab51abcc1491bff22fc80d902bb252d6f9c5399fea26e7&sso_ip=65a13da4931d082a88fc6afe3aa9a675";
map_lnyk["gkzy"]="http://zz.api.ks5u.com";
map_lnyk["pingk"]="http://pkln.czbanbantong.com";
map_lnyk["ubi"]="http://ubln.czbanbantong.com";
map_lnyk["vfs"]="http://vfsln.czbanbantong.com";
map_lnyk["micro"]="http://wkln.czbanbantong.com";
map_lnyk["area"]="lnyk";
mapObj["42."]=map_lnyk;
//天津
var map_tj = {};  
map_tj["portal"]="http://tj.czbanbantong.com";
map_tj["pls"]="http://plstj.czbanbantong.com";
map_tj["cms"]="http://vfstj.czbanbantong.com";
map_tj["tms"]="http://tmstj.czbanbantong.com";
map_tj["tqms"]="http://tqmstj.czbanbantong.com";
map_tj["sso"]="http://ssotj.czbanbantong.com";
map_tj["ilearn"]="http://ilearntj.czbanbantong.com";
map_tj["eng"]="http://en.czbanbantong.com";
map_tj["statpv"]="statpvtj.czbanbantong.com";
map_tj["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_tj["nbsy"]="http://nbtj.czbanbantong.com/experiment/index/wuli?sso=00ef7d60bf3d2efa0b22ab825d1a46872b5ca973eb2e08f3&sso_ip=65a13da4931d082a9adfae3a4714d3bf";
map_tj["gkzy"]="http://zz.api.ks5u.com";
map_tj["pingk"]="http://pktj.czbanbantong.com";
map_tj["ubi"]="http://ubtj.czbanbantong.com";
map_tj["vfs"]="http://vfstj.czbanbantong.com";
map_tj["micro"]="http://wktj.czbanbantong.com";
map_tj["area"]="tj";
mapObj["11."]=map_tj;

//北京
var map_bj = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_bj["portal"]="http://bj.czbanbantong.com";
map_bj["pls"]="http://plstj.czbanbantong.com";
map_bj["cms"]="http://vfstj.czbanbantong.com";
map_bj["tms"]="http://tmstj.czbanbantong.com";
map_bj["tqms"]="http://tqmstj.czbanbantong.com";
map_bj["sso"]="http://ssobj.czbanbantong.com";
map_bj["ilearn"]="http://ilearntj.czbanbantong.com";
map_bj["eng"]="http://en.czbanbantong.com";
map_bj["statpv"]="statpvtj.czbanbantong.com";
map_bj["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_bj["nbsy"]="http://nbtj.czbanbantong.com/experiment/index/wuli?sso=00ef7d60bf3d2efa0b22ab825d1a46872b5ca973eb2e08f3&sso_ip=65a13da4931d082a9adfae3a4714d3bf";
map_bj["gkzy"]="http://zz.api.ks5u.com";
map_bj["pingk"]="http://pktj.czbanbantong.com";
map_bj["ubi"]="http://ubtj.czbanbantong.com";
map_bj["vfs"]="http://vfstj.czbanbantong.com";
map_bj["micro"]="http://wktj.czbanbantong.com";
map_bj["area"]="bj";
mapObj["24."]=map_bj;


//甘肃
var map_gs = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_gs["portal"]="http://gs.czbanbantong.com";
map_gs["pls"]="http://plsgs.czbanbantong.com";
map_gs["cms"]="http://vfsgs.czbanbantong.com";
map_gs["tms"]="http://tmsgs.czbanbantong.com";
map_gs["tqms"]="http://tqmsgs.czbanbantong.com";
map_gs["sso"]="http://ssogs.czbanbantong.com";
map_gs["ilearn"]="http://ilearngs.czbanbantong.com";
map_gs["eng"]="http://en.czbanbantong.com";
map_gs["statpv"]="statpvgs.czbanbantong.com";
map_gs["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_gs["nbsy"]="http://nbgs.czbanbantong.com/experiment/index/wuli?sso=6fe8aff2308b46a095911acfec80692686040d797a00f5f4&sso_ip=ae5b1b5a3c2b0e3537928e849e2a2335";
map_gs["gkzy"]="http://zz.api.ks5u.com";
map_gs["pingk"]="http://pkgs.czbanbantong.com";
map_gs["ubi"]="http://ubgs.czbanbantong.com";
map_gs["vfs"]="http://vfsgs.czbanbantong.com";
map_gs["micro"]="http://wkgs.czbanbantong.com";
map_gs["area"]="gs";
mapObj["5."]=map_gs;
//新疆
var map_xj = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_xj["portal"]="http://xj.czbanbantong.com";
map_xj["pls"]="http://plsgs.czbanbantong.com";
map_xj["cms"]="http://vfsgs.czbanbantong.com";
map_xj["tms"]="http://tmsgs.czbanbantong.com";
map_xj["tqms"]="http://tqmsgs.czbanbantong.com";
map_xj["sso"]="http://ssoxj.czbanbantong.com";
map_xj["ilearn"]="http://ilearngs.czbanbantong.com";
map_xj["eng"]="http://en.czbanbantong.com";
map_xj["statpv"]="statpvgs.czbanbantong.com";
map_xj["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_xj["nbsy"]="http://nbgs.czbanbantong.com/experiment/index/wuli?sso=6fe8aff2308b46a095911acfec80692686040d797a00f5f4&sso_ip=ae5b1b5a3c2b0e3537928e849e2a2335";
map_xj["gkzy"]="http://zz.api.ks5u.com";
map_xj["pingk"]="http://pkgs.czbanbantong.com";
map_xj["ubi"]="http://ubgs.czbanbantong.com";
map_xj["vfs"]="http://vfsgs.czbanbantong.com";
map_xj["micro"]="http://wkgs.czbanbantong.com";
map_xj["area"]="xj";
mapObj["22."]=map_xj;

//20160428哈密、新疆兵团共建甘肃
var map_xjbt = {};  
map_xjbt["portal"]="http://xjbt.czbanbantong.com";
map_xjbt["pls"]="http://plsgs.czbanbantong.com";
map_xjbt["cms"]="http://vfsgs.czbanbantong.com";
map_xjbt["tms"]="http://tmsgs.czbanbantong.com";
map_xjbt["tqms"]="http://tqmsgs.czbanbantong.com";
map_xjbt["sso"]="http://ssoxjbt.czbanbantong.com";
map_xjbt["ilearn"]="http://ilearngs.czbanbantong.com";
map_xjbt["eng"]="http://en.czbanbantong.com";
map_xjbt["statpv"]="statpvgs.czbanbantong.com";
map_xjbt["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_xjbt["nbsy"]="http://nbgs.czbanbantong.com/experiment/index/wuli?sso=6fe8aff2308b46a095911acfec80692686040d797a00f5f4&sso_ip=ae5b1b5a3c2b0e3537928e849e2a2335";
map_xjbt["gkzy"]="http://zz.api.ks5u.com";
map_xjbt["pingk"]="http://pkgs.czbanbantong.com";
map_xjbt["ubi"]="http://ubgs.czbanbantong.com";
map_xjbt["vfs"]="http://vfsgs.czbanbantong.com";
map_xjbt["micro"]="http://wkgs.czbanbantong.com";
map_xjbt["area"]="xjbt";
mapObj["43."]=map_xjbt;
//青海
var map_qh = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_qh["portal"]="http://gs.czbanbantong.com";
map_qh["pls"]="http://plsgs.czbanbantong.com";
map_qh["cms"]="http://vfsgs.czbanbantong.com";
map_qh["tms"]="http://tmsgs.czbanbantong.com";
map_qh["tqms"]="http://tqmsgs.czbanbantong.com";
map_qh["sso"]="http://ssoqh.czbanbantong.com";
map_qh["ilearn"]="http://ilearngs.czbanbantong.com";
map_qh["eng"]="http://en.czbanbantong.com";
map_qh["statpv"]="statpvgs.czbanbantong.com";
map_qh["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_qh["nbsy"]="http://nbgs.czbanbantong.com/experiment/index/wuli?sso=6fe8aff2308b46a095911acfec80692686040d797a00f5f4&sso_ip=ae5b1b5a3c2b0e3537928e849e2a2335";
map_qh["gkzy"]="http://zz.api.ks5u.com";
map_qh["pingk"]="http://pkgs.czbanbantong.com";
map_qh["vfs"]="http://vfsgs.czbanbantong.com";
map_qh["ubi"]="http://ubgs.czbanbantong.com";
map_qh["micro"]="http://wkgs.czbanbantong.com";
map_qh["area"]="qh";
mapObj["26."]=map_qh;
//陕西
var map_sn = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_sn["portal"]="http://sn.czbanbantong.com";
map_sn["pls"]="http://plssn.czbanbantong.com";
map_sn["cms"]="http://vfssn.czbanbantong.com";
map_sn["tms"]="http://tmssn.czbanbantong.com";
map_sn["tqms"]="http://tqmssn.czbanbantong.com";
map_sn["sso"]="http://ssosn.czbanbantong.com";
map_sn["ilearn"]="http://ilearnsn.czbanbantong.com";
map_sn["eng"]="http://en.czbanbantong.com";
map_sn["statpv"]="statpvsn.czbanbantong.com";
map_sn["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_sn["nbsy"]="http://nbsn.czbanbantong.com/experiment/index/wuli?sso=c70f90be3aae8005cd9547ba2a5d1828ecea5cf2aa21874b&sso_ip=65a13da4931d082a00f6ef7a1d3c00d7";
map_sn["gkzy"]="http://zz.api.ks5u.com";
map_sn["pingk"]="http://pksn.czbanbantong.com";
map_sn["ubi"]="http://ubsn.czbanbantong.com";
map_sn["vfs"]="http://vfssn.czbanbantong.com";
map_sn["micro"]="http://wksn.czbanbantong.com";
map_sn["area"]="sn";
mapObj["18."]=map_sn;

//宁夏
var map_nx = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_nx["portal"]="http://nx.czbanbantong.com";
map_nx["pls"]="http://plssn.czbanbantong.com";
map_nx["cms"]="http://vfssn.czbanbantong.com";
map_nx["tms"]="http://tmssn.czbanbantong.com";
map_nx["tqms"]="http://tqmssn.czbanbantong.com";
map_nx["sso"]="http://ssonx.czbanbantong.com";
map_nx["ilearn"]="http://ilearnsn.czbanbantong.com";
map_nx["eng"]="http://en.czbanbantong.com";
map_nx["statpv"]="statpvsn.czbanbantong.com";
map_nx["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_nx["nbsy"]="http://nbsn.czbanbantong.com/experiment/index/wuli?sso=c70f90be3aae8005cd9547ba2a5d1828ecea5cf2aa21874b&sso_ip=65a13da4931d082a00f6ef7a1d3c00d7";
map_nx["gkzy"]="http://zz.api.ks5u.com";
map_nx["pingk"]="http://pksn.czbanbantong.com";
map_nx["ubi"]="http://ubsn.czbanbantong.com";
map_nx["vfs"]="http://vfssn.czbanbantong.com";
map_nx["micro"]="http://wksn.czbanbantong.com";
map_nx["area"]="nx";
mapObj["20."]=map_nx;

//西藏
var map_xz = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_xz["portal"]="http://xz.czbanbantong.com";
map_xz["pls"]="http://plssn.czbanbantong.com";
map_xz["cms"]="http://vfssn.czbanbantong.com";
map_xz["tms"]="http://tmssn.czbanbantong.com";
map_xz["tqms"]="http://tqmssn.czbanbantong.com";
map_xz["sso"]="http://ssoxz.czbanbantong.com";
map_xz["ilearn"]="http://ilearnsn.czbanbantong.com";
map_xz["eng"]="http://en.czbanbantong.com";
map_xz["statpv"]="statpvsn.czbanbantong.com";
map_xz["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_xz["nbsy"]="http://nbsn.czbanbantong.com/experiment/index/wuli?sso=c70f90be3aae8005cd9547ba2a5d1828ecea5cf2aa21874b&sso_ip=65a13da4931d082a00f6ef7a1d3c00d7";
map_xz["gkzy"]="http://zz.api.ks5u.com";
map_xz["pingk"]="http://pksn.czbanbantong.com";
map_xz["ubi"]="http://ubsn.czbanbantong.com";
map_xz["vfs"]="http://vfssn.czbanbantong.com";
map_xz["micro"]="http://wksn.czbanbantong.com";
map_xz["area"]="xz";
mapObj["21."]=map_xz;
//山西
var map_sx = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_sx["portal"]="http://sx.czbanbantong.com";
map_sx["pls"]="http://plssx.czbanbantong.com";
map_sx["cms"]="http://vfssx.czbanbantong.com";
map_sx["tms"]="http://tmssx.czbanbantong.com";
map_sx["tqms"]="http://tqmssx.czbanbantong.com";
map_sx["sso"]="http://ssosx.czbanbantong.com";
map_sx["ilearn"]="http://ilearnsx.czbanbantong.com";
map_sx["eng"]="http://en.czbanbantong.com";
map_sx["statpv"]="statpvsx.czbanbantong.com";
map_sx["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_sx["nbsy"]="http://nbsx.czbanbantong.com/experiment/index/wuli?sso=aa2a0205130dd1d7d052611a704322d7f2f92dc1cddc6995&sso_ip=c14c58706c16eecda0d2ce84922d0068";
map_sx["gkzy"]="http://zz.api.ks5u.com";
map_sx["pingk"]="http://pksx.czbanbantong.com";
map_sx["ubi"]="http://ubsx.czbanbantong.com";
map_sx["vfs"]="http://vfssx.czbanbantong.com";
map_sx["micro"]="http://wksx.czbanbantong.com";
map_sx["area"]="sx";
mapObj["10."]=map_sx;

//内蒙
var map_nm = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_nm["portal"]="http://nm.czbanbantong.com";
map_nm["pls"]="http://plsnm.czbanbantong.com";
map_nm["cms"]="http://vfsnm.czbanbantong.com";
map_nm["tms"]="http://tmsnm.czbanbantong.com";
map_nm["tqms"]="http://tqmsnm.czbanbantong.com";
map_nm["sso"]="http://ssonm.czbanbantong.com";
map_nm["ilearn"]="http://ilearnnm.czbanbantong.com";
map_nm["eng"]="http://en.czbanbantong.com";
map_nm["statpv"]="statpvnm.czbanbantong.com";
map_nm["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_nm["nbsy"]="http://nbnm.czbanbantong.com/experiment/index/wuli?sso=061c1def67420f2bb5be6f85a32a4f677bc2bacf6d6f2ad1&sso_ip=a375f58263714f6bf98cee7301fcadd8";
map_nm["gkzy"]="http://zz.api.ks5u.com";
map_nm["pingk"]="http://pknm.czbanbantong.com";
map_nm["ubi"]="http://ubnm.czbanbantong.com";
map_nm["vfs"]="http://vfsnm.czbanbantong.com";
map_nm["micro"]="http://wknm.czbanbantong.com";
map_nm["area"]="nm";
mapObj["23."]=map_nm;
//内蒙呼和浩特 20160516添加
var map_hhht = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_hhht["portal"]="http://hhht.czbanbantong.com";
map_hhht["pls"]="http://plsnm.czbanbantong.com";
map_hhht["cms"]="http://vfsnm.czbanbantong.com";
map_hhht["tms"]="http://tmsnm.czbanbantong.com";
map_hhht["tqms"]="http://tqmsnm.czbanbantong.com";
map_hhht["sso"]="http://ssohhht.czbanbantong.com";
map_hhht["ilearn"]="http://ilearnnm.czbanbantong.com";
map_hhht["eng"]="http://en.czbanbantong.com";
map_hhht["statpv"]="statpvnm.czbanbantong.com";
map_hhht["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_hhht["nbsy"]="http://nbnm.czbanbantong.com/experiment/index/wuli?sso=061c1def67420f2bb5be6f85a32a4f677bc2bacf6d6f2ad1&sso_ip=a375f58263714f6bf98cee7301fcadd8";
map_hhht["gkzy"]="http://zz.api.ks5u.com";
map_hhht["pingk"]="http://pknm.czbanbantong.com";
map_hhht["ubi"]="http://ubnm.czbanbantong.com";
map_hhht["vfs"]="http://vfsnm.czbanbantong.com";
map_hhht["micro"]="http://wknm.czbanbantong.com";
map_hhht["area"]="hhht";
mapObj["45."]=map_hhht;

//内蒙海拉尔 20160722添加
var map_hle = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_hle["portal"]="http://hle.czbanbantong.com";
map_hle["pls"]="http://plsnm.czbanbantong.com";
map_hle["cms"]="http://vfsnm.czbanbantong.com";
map_hle["tms"]="http://tmsnm.czbanbantong.com";
map_hle["tqms"]="http://tqmsnm.czbanbantong.com";
map_hle["sso"]="http://ssohle.czbanbantong.com";
map_hle["ilearn"]="http://ilearnnm.czbanbantong.com";
map_hle["eng"]="http://en.czbanbantong.com";
map_hle["statpv"]="statpvnm.czbanbantong.com";
map_hle["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_hle["nbsy"]="http://nbnm.czbanbantong.com/experiment/index/wuli?sso=061c1def67420f2bb5be6f85a32a4f677bc2bacf6d6f2ad1&sso_ip=a375f58263714f6bf98cee7301fcadd8";
map_hle["gkzy"]="http://zz.api.ks5u.com";
map_hle["pingk"]="http://pknm.czbanbantong.com";
map_hle["ubi"]="http://ubnm.czbanbantong.com";
map_hle["vfs"]="http://vfsnm.czbanbantong.com";
map_hle["micro"]="http://wknm.czbanbantong.com";
map_hle["area"]="hle";
mapObj["47."]=map_hle;

//安徽
var map_ah = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_ah["portal"]="http://ah.czbanbantong.com";
map_ah["pls"]="http://plsah.czbanbantong.com";
map_ah["cms"]="http://vfsah.czbanbantong.com";
map_ah["tms"]="http://tmsah.czbanbantong.com";
map_ah["tqms"]="http://tqmsah.czbanbantong.com";
map_ah["sso"]="http://ssoah.czbanbantong.com";
map_ah["ilearn"]="http://ilearnah.czbanbantong.com";
map_ah["eng"]="http://en.czbanbantong.com";
map_ah["statpv"]="statpvah.czbanbantong.com";
map_ah["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_ah["nbsy"]="http://nbah.czbanbantong.com/experiment/index/wuli?sso=b45f1d68db71ace9d0e3bc249c840e94afc3b02f1672ea55&sso_ip=65a13da4931d082ae74dd80fc8424c52";
map_ah["gkzy"]="http://zz.api.ks5u.com";
map_ah["pingk"]="http://pkah.czbanbantong.com";
map_ah["ubi"]="http://ubah.czbanbantong.com";
map_ah["vfs"]="http://vfsah.czbanbantong.com";
map_ah["micro"]="http://wkah.czbanbantong.com";
map_ah["area"]="ah";
mapObj["15."]=map_ah;
//江苏
var map_js = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_js["portal"]="http://js.czbanbantong.com";
map_js["pls"]="http://plsjs.czbanbantong.com";
map_js["cms"]="http://vfsjs.czbanbantong.com";
map_js["tms"]="http://tmsjs.czbanbantong.com";
map_js["tqms"]="http://tqmsjs.czbanbantong.com";
map_js["sso"]="http://ssojs.czbanbantong.com";
map_js["ilearn"]="http://ilearnjs.czbanbantong.com";
map_js["eng"]="http://en.czbanbantong.com";
map_js["statpv"]="statpvjs.czbanbantong.com";
map_js["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_js["nbsy"]="http://nbjs.czbanbantong.com/experiment/index/wuli?sso=2c2134cd9f666b890c1c5118bbde25803a243638e9c765be&sso_ip=65a13da4931d082a60affb2f882c7a1b";
map_js["gkzy"]="http://zz.api.ks5u.com";
map_js["pingk"]="http://pkjs.czbanbantong.com";
map_js["ubi"]="http://ubjs.czbanbantong.com";
map_js["vfs"]="http://vfsjs.czbanbantong.com";
map_js["micro"]="http://wkjs.czbanbantong.com";
map_js["area"]="js";
mapObj["14."]=map_js;
//广西
var map_gx = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_gx["portal"]="http://gx.czbanbantong.com";
map_gx["pls"]="http://plsgx.czbanbantong.com";
map_gx["cms"]="http://vfsgx.czbanbantong.com";
map_gx["tms"]="http://tmsgx.czbanbantong.com";
map_gx["tqms"]="http://tqmsgx.czbanbantong.com";
map_gx["sso"]="http://ssogx.czbanbantong.com";
map_gx["ilearn"]="http://ilearngx.czbanbantong.com";
map_gx["eng"]="http://en.czbanbantong.com";
map_gx["statpv"]="statpvgx.czbanbantong.com";
map_gx["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_gx["nbsy"]="http://nbgx.czbanbantong.com/experiment/index/wuli?sso=394b3d43b0563e53ec2f0629dcaccd7f4741fb1a30a06083&sso_ip=65a13da4931d082a0c88079b21db326e";
map_gx["gkzy"]="http://zz.api.ks5u.com";
map_gx["pingk"]="http://pkgx.czbanbantong.com";
map_gx["ubi"]="http://ubgx.czbanbantong.com";
map_gx["vfs"]="http://vfsgx.czbanbantong.com";
map_gx["micro"]="http://wkgx.czbanbantong.com";
map_gx["area"]="gx";
mapObj["12."]=map_gx;

//桂林
var map_guilin = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_guilin["portal"]="http://guilin.czbanbantong.com";
map_guilin["pls"]="http://plsgx.czbanbantong.com";
map_guilin["cms"]="http://vfsgx.czbanbantong.com";
map_guilin["tms"]="http://tmsgx.czbanbantong.com";
map_guilin["tqms"]="http://tqmsgx.czbanbantong.com";
map_guilin["sso"]="http://ssoguilin.czbanbantong.com";
map_guilin["ilearn"]="http://ilearngx.czbanbantong.com";
map_guilin["eng"]="http://en.czbanbantong.com";
map_guilin["crm"]="http://crmgx.czbanbantong.com";
map_guilin["statpv"]="statpvgx.czbanbantong.com";
map_guilin["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_guilin["nbsy"]="http://nbgx.czbanbantong.com/experiment/index/wuli?sso=394b3d43b0563e53ec2f0629dcaccd7f4741fb1a30a06083&sso_ip=65a13da4931d082a0c88079b21db326e";
map_guilin["gkzy"]="http://zz.api.ks5u.com";
map_guilin["pingk"]="http://pkgx.czbanbantong.com";
map_guilin["ubi"]="http://ubgx.czbanbantong.com";
map_guilin["vfs"]="http://vfsgx.czbanbantong.com";
map_guilin["micro"]="http://wkgx.czbanbantong.com";
map_guilin["area"]="guilin";
mapObj["32."]=map_guilin;
//广东
var map_gd = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_gd["portal"]="http://gd.czbanbantong.com";
map_gd["pls"]="http://plsgd.czbanbantong.com";
map_gd["cms"]="http://vfsgd.czbanbantong.com";
map_gd["tms"]="http://tmsgd.czbanbantong.com";
map_gd["tqms"]="http://tqmsgd.czbanbantong.com";
map_gd["sso"]="http://ssogd.czbanbantong.com";
map_gd["ilearn"]="http://ilearngd.czbanbantong.com";
map_gd["eng"]="http://en.czbanbantong.com";
map_gd["statpv"]="statpvgd.czbanbantong.com";
map_gd["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_gd["nbsy"]="http://nbgd.czbanbantong.com/experiment/index/wuli?sso=c04782433f1878ac422c8ec7cd85c3d14193e4b842a1ecf9&sso_ip=65a13da4931d082a6c58ba65a052f00d";
map_gd["gkzy"]="http://zz.api.ks5u.com";
map_gd["pingk"]="http://pkgd.czbanbantong.com";
map_gd["ubi"]="http://ubgd.czbanbantong.com";
map_gd["vfs"]="http://vfsgd.czbanbantong.com";
map_gd["micro"]="http://wkgd.czbanbantong.com";
map_gd["area"]="gd";
mapObj["17."]=map_gd;

//海南
var map_hi = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_hi["portal"]="http://hi.czbanbantong.com";
map_hi["pls"]="http://plsgd.czbanbantong.com";
map_hi["cms"]="http://vfsgd.czbanbantong.com";
map_hi["tms"]="http://tmsgd.czbanbantong.com";
map_hi["tqms"]="http://tqmsgd.czbanbantong.com";
map_hi["sso"]="http://ssohi.czbanbantong.com";
map_hi["ilearn"]="http://ilearngd.czbanbantong.com";
map_hi["eng"]="http://en.czbanbantong.com";
map_hi["statpv"]="statpvgd.czbanbantong.com";
map_hi["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_hi["nbsy"]="http://nbgd.czbanbantong.com/experiment/index/wuli?sso=c04782433f1878ac422c8ec7cd85c3d14193e4b842a1ecf9&sso_ip=65a13da4931d082a6c58ba65a052f00d";
map_hi["gkzy"]="http://zz.api.ks5u.com";
map_hi["pingk"]="http://pkgd.czbanbantong.com";
map_hi["ubi"]="http://ubgd.czbanbantong.com";
map_hi["vfs"]="http://vfsgd.czbanbantong.com";
map_hi["micro"]="http://wkgd.czbanbantong.com";
map_hi["area"]="hi";
mapObj["29."]=map_hi;
//云南
var map_yn = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_yn["portal"]="http://yn.czbanbantong.com";
map_yn["pls"]="http://plsyn.czbanbantong.com";
map_yn["cms"]="http://vfsyn.czbanbantong.com";
map_yn["tms"]="http://tmsyn.czbanbantong.com";
map_yn["tqms"]="http://tqmsyn.czbanbantong.com";
map_yn["sso"]="http://ssoyn.czbanbantong.com";
map_yn["ilearn"]="http://ilearnyn.czbanbantong.com";
map_yn["eng"]="http://en.czbanbantong.com";
map_yn["statpv"]="statpvyn.czbanbantong.com";
map_yn["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_yn["nbsy"]="http://nbyn.czbanbantong.com/experiment/index/wuli?sso=e0d04a909906c331052d27c3bab318050b15e1fb864babb5&sso_ip=cfb32a57eaeb3ea78cc771ded4ebfdc9";
map_yn["gkzy"]="http://zz.api.ks5u.com";
map_yn["pingk"]="http://pkyn.czbanbantong.com";
map_yn["ubi"]="http://ubyn.czbanbantong.com";
map_yn["vfs"]="http://vfsyn.czbanbantong.com";
map_yn["micro"]="http://wkyn.czbanbantong.com";
map_yn["area"]="yn";
mapObj["9."]=map_yn;

//襄阳
var map_xy = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_xy["portal"]="http://xy.czbanbantong.com";
map_xy["pls"]="http://plsxy.czbanbantong.com";
map_xy["cms"]="http://vfsxy.czbanbantong.com";
map_xy["tms"]="http://tmsxy.czbanbantong.com";
map_xy["tqms"]="http://tqmsxy.czbanbantong.com";
map_xy["sso"]="http://ssoxy.czbanbantong.com";
map_xy["ilearn"]="http://ilearnxy.czbanbantong.com";
map_xy["eng"]="http://en.czbanbantong.com";
map_xy["statpv"]="statpvxy.czbanbantong.com";
map_xy["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_xy["nbsy"]="http://nbxy.czbanbantong.com/experiment/index/wuli?sso=41b8eaeaf08e52ca88594d8fd3d8024c3c50f4ca51ab3550&sso_ip=65a13da4931d082a878820ef30c46f6e";
map_xy["gkzy"]="http://zz.api.ks5u.com";
map_xy["pingk"]="http://pkxy.czbanbantong.com";
map_xy["ubi"]="http://ubxy.czbanbantong.com";
map_xy["vfs"]="http://vfsxy.czbanbantong.com";
map_xy["micro"]="http://wkxy.czbanbantong.com";
map_xy["area"]="xy";
mapObj["19."]=map_xy;
//北镇
var map_jz = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_jz["portal"]="http://jz.czbanbantong.com";
map_jz["pls"]="http://plsjz.czbanbantong.com";
map_jz["cms"]="http://vfsjz.czbanbantong.com";
map_jz["tms"]="http://tmsjz.czbanbantong.com";
map_jz["tqms"]="http://tqmsjz.czbanbantong.com";
map_jz["sso"]="http://ssojz.czbanbantong.com";
map_jz["ilearn"]="http://ilearnjz.czbanbantong.com";
map_jz["eng"]="http://en.czbanbantong.com";
map_jz["statpv"]="statpvjz.czbanbantong.com";
map_jz["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_jz["nbsy"]="http://nbjz.czbanbantong.com/experiment/index/wuli?sso=8846ac61b22ff64b1d06f8aabd252849903f16dc79f6bb51&sso_ip=a375f58263714f6b2429ddb478c6694a";
map_jz["gkzy"]="http://zz.api.ks5u.com";
map_jz["pingk"]="http://pkjz.czbanbantong.com";
map_jz["ubi"]="http://ubjz.czbanbantong.com";
map_jz["vfs"]="http://vfsjz.czbanbantong.com";
map_jz["micro"]="http://wkjz.czbanbantong.com";
map_jz["area"]="jz";
mapObj["31."]=map_jz;
//湖南
var map_hn = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_hn["portal"]="http://hn.czbanbantong.com";
map_hn["pls"]="http://plshn.czbanbantong.com";
map_hn["cms"]="http://vfshn.czbanbantong.com";
map_hn["tms"]="http://tmshn.czbanbantong.com";
map_hn["tqms"]="http://tqmshn.czbanbantong.com";
map_hn["sso"]="http://ssohn.czbanbantong.com";
map_hn["ilearn"]="http://ilearnhn.czbanbantong.com";
map_hn["eng"]="http://en.czbanbantong.com";
map_hn["statpv"]="statpvhn.czbanbantong.com";
map_hn["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_hn["nbsy"]="http://nbhn.czbanbantong.com/experiment/index/wuli?sso=a36811c7ccbbec77aab20fd7b91f821c6de530a9f8a7b944&sso_ip=a375f58263714f6bbd7923d9a6b7341f";
map_hn["gkzy"]="http://zz.api.ks5u.com";
map_hn["pingk"]="http://pkhn.czbanbantong.com";
map_hn["ubi"]="http://ubhn.czbanbantong.com";
map_hn["vfs"]="http://vfshn.czbanbantong.com";
map_hn["micro"]="http://wkhn.czbanbantong.com";
map_hn["area"]="hn";
mapObj["28."]=map_hn;

//湖北20150527增加
var map_hb = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_hb["portal"]="http://hb.czbanbantong.com";
map_hb["pls"]="http://plshb.czbanbantong.com";
map_hb["cms"]="http://vfshb.czbanbantong.com";
map_hb["tms"]="http://tmshb.czbanbantong.com";
map_hb["tqms"]="http://tqmshb.czbanbantong.com";
map_hb["sso"]="http://ssohb.czbanbantong.com";
map_hb["ilearn"]="http://ilearnhb.czbanbantong.com";
map_hb["eng"]="http://en.czbanbantong.com";
map_hb["statpv"]="statpvhb.czbanbantong.com";
map_hb["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_hb["nbsy"]="http://nbhb.czbanbantong.com/experiment/index/wuli?sso=a36811c7ccbbec77aab20fd7b91f821c6de530a9f8a7b944&sso_ip=a375f58263714f6bbd7923d9a6b7341f";
map_hb["gkzy"]="http://zz.api.ks5u.com";
map_hb["pingk"]="http://pkhb.czbanbantong.com";
map_hb["ubi"]="http://ubhb.czbanbantong.com";
map_hb["vfs"]="http://vfshb.czbanbantong.com";
map_hb["micro"]="http://wkhb.czbanbantong.com";
map_hb["area"]="hb";
mapObj["37."]=map_hb;
//湖北汉阳20151215增加
var map_hbhy = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_hbhy["portal"]="http://hbhy.czbanbantong.com";
map_hbhy["pls"]="http://plshb.czbanbantong.com";
map_hbhy["cms"]="http://vfshb.czbanbantong.com";
map_hbhy["tms"]="http://tmshb.czbanbantong.com";
map_hbhy["tqms"]="http://tqmshb.czbanbantong.com";
map_hbhy["sso"]="http://ssohbhy.czbanbantong.com";
map_hbhy["ilearn"]="http://ilearnhb.czbanbantong.com";
map_hbhy["eng"]="http://en.czbanbantong.com";
map_hbhy["statpv"]="statpvhb.czbanbantong.com";
map_hbhy["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_hbhy["nbsy"]="http://nbhb.czbanbantong.com/experiment/index/wuli?sso=a36811c7ccbbec77aab20fd7b91f821c6de530a9f8a7b944&sso_ip=a375f58263714f6bbd7923d9a6b7341f";
map_hbhy["gkzy"]="http://zz.api.ks5u.com";
map_hbhy["pingk"]="http://pkhb.czbanbantong.com";
map_hbhy["ubi"]="http://ubhb.czbanbantong.com";
map_hbhy["vfs"]="http://vfshb.czbanbantong.com";
map_hbhy["micro"]="http://wkhb.czbanbantong.com";
map_hbhy["area"]="hbhy";
mapObj["38."]=map_hbhy;
//山西大同
var map_dt = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_dt["portal"]="http://dt.czbanbantong.com";
map_dt["pls"]="http://plsdt.czbanbantong.com";
map_dt["cms"]="http://vfsdt.czbanbantong.com";
map_dt["tms"]="http://tmsdt.czbanbantong.com";
map_dt["tqms"]="http://tqmsdt.czbanbantong.com";
map_dt["sso"]="http://ssodt.czbanbantong.com";
map_dt["ilearn"]="http://ilearndt.czbanbantong.com";
map_dt["eng"]="http://en.czbanbantong.com";
map_dt["statpv"]="statpvdt.czbanbantong.com";
map_dt["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_dt["nbsy"]="http://nbdt.czbanbantong.com/experiment/index/wuli?sso=1e9ae75761f2ddd242289178973c6052b334f4fde675346b&sso_ip=b362363c64c6d0dec46f28523681be70";
map_dt["gkzy"]="http://zz.api.ks5u.com";
map_dt["pingk"]="http://pkdt.czbanbantong.com";
map_dt["ubi"]="http://ubdt.czbanbantong.com";
map_dt["vfs"]="http://vfsdt.czbanbantong.com";
map_dt["micro"]="http://wkdt.czbanbantong.com";
map_dt["area"]="dt";
mapObj["33."]=map_dt;

//科威
var map_kw = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_kw["portal"]="http://kw.czbanbantong.com";
map_kw["pls"]="http://plskw.czbanbantong.com";
map_kw["cms"]="http://vfskw.czbanbantong.com";
map_kw["tms"]="http://tmskw.czbanbantong.com";
map_kw["tqms"]="http://tqmskw.czbanbantong.com";
map_kw["sso"]="http://ssokw.czbanbantong.com";
map_kw["ilearn"]="http://ilearnkw.czbanbantong.com";
map_kw["eng"]="http://en.czbanbantong.com";
map_kw["statpv"]="statpvkw.czbanbantong.com";
map_kw["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_kw["nbsy"]="http://nbkw.czbanbantong.com/experiment/index/wuli?sso=d87dd3c673a0c33e87c6ecf5cee5ee71cdb7dc091c2190cb&sso_ip=6a505e4a9e891b70fce306da59f66d63";
map_kw["gkzy"]="http://zz.api.ks5u.com";
map_kw["pingk"]="http://pkkw.czbanbantong.com";
map_kw["ubi"]="http://ubkw.czbanbantong.com";
map_kw["vfs"]="http://vfskw.czbanbantong.com";
map_kw["micro"]="http://wkkw.czbanbantong.com";
map_kw["area"]="kw";
mapObj["34."]=map_kw;

//华为 科威共建  20160722添加
var map_hw = {};   //内层集合对象，存放河南地区系统编码以及对应的域名
map_hw["portal"]="http://hw.czbanbantong.com";
map_hw["pls"]="http://plskw.czbanbantong.com";
map_hw["cms"]="http://vfskw.czbanbantong.com";
map_hw["tms"]="http://tmskw.czbanbantong.com";
map_hw["tqms"]="http://tqmskw.czbanbantong.com";
map_hw["sso"]="http://ssohw.czbanbantong.com";
map_hw["ilearn"]="http://ilearnkw.czbanbantong.com";
map_hw["eng"]="http://en.czbanbantong.com";
map_hw["statpv"]="statpvkw.czbanbantong.com";
map_hw["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_hw["nbsy"]="http://nbkw.czbanbantong.com/experiment/index/wuli?sso=d87dd3c673a0c33e87c6ecf5cee5ee71cdb7dc091c2190cb&sso_ip=6a505e4a9e891b70fce306da59f66d63";
map_hw["gkzy"]="http://zz.api.ks5u.com";
map_hw["pingk"]="http://pkkw.czbanbantong.com";
map_hw["ubi"]="http://ubkw.czbanbantong.com";
map_hw["vfs"]="http://vfskw.czbanbantong.com";
map_hw["micro"]="http://wkkw.czbanbantong.com";
map_hw["area"]="hw";
mapObj["46."]=map_hw;


//德阳 20150512增加
var map_dy = {};   
map_dy["portal"]="http://dy.czbanbantong.com";
map_dy["pls"]="http://plsdy.czbanbantong.com";
map_dy["cms"]="http://vfsdy.czbanbantong.com";
map_dy["tms"]="http://tmsdy.czbanbantong.com";
map_dy["tqms"]="http://tqmsdy.czbanbantong.com";
map_dy["sso"]="http://ssody.czbanbantong.com";
map_dy["ilearn"]="http://ilearndy.czbanbantong.com";
map_dy["eng"]="http://en.czbanbantong.com";
map_dy["statpv"]="statpvdy.czbanbantong.com";
map_dy["qikan"]="http://bbtrrtxs.vip.qikan.com";
map_dy["nbsy"]="http://nbdy.czbanbantong.com/experiment/index/wuli?sso=187abcf0039b63bd82bf0a21462ffddfbb643376ee9b0d46&sso_ip=a375f58263714f6b2a951f97163bdaf0";
map_dy["gkzy"]="http://zz.api.ks5u.com";
map_dy["pingk"]="http://pkdy.czbanbantong.com";
map_dy["ubi"]="http://ubdy.czbanbantong.com";
map_dy["vfs"]="http://vfsdy.czbanbantong.com";
map_dy["micro"]="http://wkdy.czbanbantong.com";
map_dy["area"]="dy";
mapObj["36."]=map_dy;
